@echo off

@REM set QT_AUTO_SCREEN_SCALE_FACTOR=0
@REM set QT_ENABLE_HIGHDPI_SCALING=1
@REM set QT_SCALE_FACTOR=1
@REM set QT_SCREEN_SCALE_FACTORS=1:1
set QT_FONT_DPI=120
@REM set QT_DEVICE_PIXEL_RATIO=
@REM set QT_SCALE_FACTOR_ROUNDING_POLICY=
@REM set QT_USE_PHYSICAL_DPI=

start "" "C:\Program Files\MATLAB\R2025a\bin\matlab.exe"
